import React, { useState } from 'react';
import './App.css'; 

function App() {
  const [audioFile, setAudioFile] = useState(null); // stores the selected audio file
  const [transcript, setTranscript] = useState(''); // stores the raw transcription
  const [notes, setNotes] = useState('');           // stores the meeting notes generated by GPT
  const [loading, setLoading] = useState(false);    // shows loading state when transcription is in progress
  const [error, setError] = useState(null);         // displays errors if any occur

  // trigggers when a user selects an audio file
  const handleFileChange = (e) => {
    setAudioFile(e.target.files[0]); // grabs the selected file and stores it in audioFile state
  };

  // triggers when the user clicks "Upload"
  const handleUpload = async () => {
    if (!audioFile) {
      alert('Please select an audio file first!');
      return;
    }

    const formData = new FormData(); // formData object is used to send files in HTTP requests
    formData.append('audio', audioFile); // attaches the slected audio file to the formData object

    try {
      setLoading(true); //tells UI that the upload is in progress
      setError(null); 
      setTranscript('');
      setNotes('');

      //sends POST req to backedn with audio file as the body and saves the response to response variable
      const response = await fetch('http://localhost:3001/transcribe', {
        method: 'POST',
        body: formData,
      });

      const data = await response.json(); // parses the response data to JSON: {transcript, notes}

      if (!response.ok) {
        throw new Error(data.error || 'Failed to process audio');
      }

      // update the states with the results from the server
      setTranscript(data.transcript);
      setNotes(data.notes);

    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="app">
      <h1>🎙️ GPT Meeting Notes Generator</h1>

      <input type="file" accept="audio/*" onChange={handleFileChange} />
      <button onClick={handleUpload} disabled={loading}>
        {loading ? 'Processing...' : 'Upload & Transcribe'}
      </button>

      {error && <p style={{ color: 'red' }}>❌ {error}</p>}

      {transcript && (
        <div className="output">
          <h2>📋 Meeting Notes:</h2>
          <pre>{notes}</pre>

          <h2>📝 Transcript:</h2>
          <pre>{transcript}</pre>
        </div>
      )}
    </div>
  );
}

export default App;
